### ISSUE TITLE
Wrong os version

### ISSUE THREAD

**Issue by x3003** [shred/identify#12]
Listexp (from identify 43.1) & scout says the os version is 3.2.1, instead of 3.2.2.1

-- ListExp V14.2 -- https://identify.shredzone.org

** HARDWARE **

System:  UAE
CPU:     68060  (Rev 6), FPU=68060 , MMU=68060
Chipset: AGA (RAMSEY None, GARY Normal, CHUNKY None) VBR=0x00000000
         DMA:   Alice 8374 Rev. 3-4 (Mode: PAL)
         Video: Lisa 4203 (Rev: 0)
         Audio: Paula 8364
         RTC:   OKI MSM6242B
AmigaOS: 3.2.1 (V47.68, SetPatch V47.8, ROM V40.68)
         Exec V47.10   Workbench V47.4
Support: GraphicOS: Picasso96, AudioOS: AHI, TCP/IP: AmiTCP/IP
Clock:   Power 50 Hz, VBlank 50 Hz, E-Clock 709379 Hz
RAM:     Motherboard 32 bit, 80 ns, Double CAS, 4x Bandwidth

Memory:            CHIP    FAST   TOTAL ROM = 512.0KB   SLOW = 0
          PLAIN  ~2.0MB   1.5GB   1.5GB
        VIRTUAL       0       0       0
          TOTAL  ~2.0MB   1.5GB   1.5GB

** EXPANSIONS **

Nr ID        Manufacturer         Product
----------------------------------------------------------------------------
 1  2011/ 96 UAE                  UAEGFX               graphics
 2 18260/ 12 MacroSystem          Toccata              audio
 3  2011/ 82 UAE                  Filesystem           HD controller
 4  2011/ 83 UAE                  Z3 Fast RAM          RAM expansion
 5  2011/ 83 UAE                  Z3 Fast RAM          RAM expansion
 6  2011/  4 UAE                  Boot ROM             expansion

**Comment by shred** [comment]
Thank you! Yes, I think it's a bug. I will have to find out the difference between AmigaOS 3.2.1 and AmigaOS 3.2.2 when installed via modules (i.e. with an older ROM, as your physical ROM is AmigaOS 3.2).

About detecting AmigaOS 3.2.2.1, I am still undecided. Actually, AmigaOS 3.2.2.1 is just an AmigaOS 3.2.2 where a few side libraries and commands have been hotfixed, so it's even less than a BoingBag. I am not sure if I really want to go down that road and support sub-sub-minor release versions.

**Comment by shred** [comment]
I located and fixed the bug. Identify will show "AmigaOS 3.2.2" on your system with the next update. If the bug still occurs after that, feel free to reopen this issue.

I decided not to call it "AmigaOS 3.2.2.1" for now, since it is only a very small hotfix update to "AmigaOS 3.2.2". If Hyperion releases more sub-sub-minor versions in the future, I may change my mind though.
