### ISSUE TITLE
Add missing expansion 5017/17 Minimig Z3 FastRAM

### ISSUE THREAD

**Issue by retrofun** [shred/identify#3]
Hi shred,

the Minimig Z3 FastRAM expansion by Alastair M. Robinson from the [MinimigAGA-MiST-TC64](https://github.com/minimig-dev/MinimigAGA-MiST-TC64/) project is missing in _identify_.

```ListExp WIDE``` outputs:
[exp_5017_17_2mb.txt](https://github.com/shred/identify/files/9692449/exp_5017_17_2mb.txt)
[exp_5017_17_4mb.txt](https://github.com/shred/identify/files/9692450/exp_5017_17_4mb.txt)

This update to ```ID_Database.s``` should add the expansion:
```
		manuf	05017,"Alastair M. Robinson"
		board	  017,"Minimig Z3 FastRAM",	MSG_EXP_RAM
		endmf	05017
```

Thanks.

**Comment by shred** [comment]
Thank you! It's added to the database now.
