### ISSUE TITLE
OS3.9 BB2 + exec.library 45.2 from BB2 = "Bad OS"

### ISSUE THREAD

**Issue by Hexaae** [shred/identify#9]
I installed latest identify.library 43.0 and noticed now Scout identifies the OS as "Bad OS" instead of expected OS3.9 (+BB3) when exec.library 45.20 is installed (included with "DEVS:AmigaOS Rom Update" from BB2)

![image](https://github.com/shred/identify/assets/8591462/515b7d75-791f-4d57-9cc0-8b3d562514d3)

**Comment by shred** [comment]
Yes, exec v45 directly leads to "unknown OS" at the moment. I will fix that.

**Comment by shred** [comment]
Should be reported as "AmigaOS 3.9" with the next release. If not, please reopen this bug.

Thank you for the report!

**Comment by Hexaae** [comment]
BTW, how does it check BBag version?

**Comment by shred** [comment]
It checks the version of `workbench.library`.
